### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by Ohto-Ai** [Ohto-Ai/QuickLook.Plugin.QtUiViewer#2]
@beiklive 我改不好了，C#与C++测试dll成功，但是打包成quick look plugin以后，运行提示找不到qt plugin，可是我在安装目录看是有的

**Comment by beiklive** [comment]
> @beiklive 我改不好了，C#与C++测试dll成功，但是打包成quick look plugin以后，运行提示找不到qt plugin，可是我在安装目录看是有的

焦头烂额，
和别的模块的人沟通了好几天，刚刚突然发现还是我的模块解析的问题，linux分页读取的问题，淦

**Comment by beiklive** [comment]
![image](https://user-images.githubusercontent.com/73771431/196893129-3f0c6d43-6761-4a51-b4f3-44c27a086927.png)
新项目，wo我感觉在这里我能把计算机网络全学完，这次做ip routing,我不知道是啥

**Comment by Ohto-Ai** [comment]
怎么感觉和我这边有点关系
